version: "3"

services:
  postgresqldb:
    container_name: pgdb
    hostname: pgdb
    image: postgres:14.1-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: cruddemo
    ports:
      - "5432:5432"
    volumes:
      - postgresqldb-data:/var/lib/postgresql/data
    networks:
      - mynet